# Generated by Django 5.1.2 on 2024-11-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dulce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('vencimiento', models.DateTimeField()),
                ('imagen', models.FileField(upload_to='dulces/')),
                ('precioCompra', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
            ],
        ),
    ]
